server:
  port: 8081
spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
logging:
  level:
    org:
      springframework:
        security: ERROR
